# =============================================================
# Simple Local Projections for Simulated Transition Path Panel
# =============================================================
#
# This script estimates very simple local projections using the simulated
# transition-path panels generated by the theoretical model. The goal is to
# measure how heterogeneity in firms' investment responses to a monetary shock
# varies with leverage and with a proxy for distance to default (cash buffers).
# The script only relies on the variables that are available in the simulated
# panels produced by `transition_path_panel.m`.


# =============================================================

suppressPackageStartupMessages({
  library(readr)
  library(dplyr)
  library(fixest)
  library(stringr)
  library(tibble)
  library(purrr)
  library(ggplot2)
  library(patchwork)
})

# ------------------------------
# Configuration
# ------------------------------
# Horizons for the local projections (in quarters)
max_forecast_horizon <- 12L
horizons <- seq_len(max_forecast_horizon)
# Monetary shock profile (same as in the MATLAB/Do-file implementation)
shock_length <- 12
shock_size <- -0.0025
shock_decay <- 0.5
shock_scale <- -4
# Winsorisation probability for financial variables
winsor_prob <- 0.005

# Directory that stores the simulated panels. The default points to the path
# used on the author's machine, but it can be overridden by defining the
# environment variable `TRANSITION_PANEL_DIR`.
default_data_dir <- "C:/Users/joser/Documents"
data_dir <- Sys.getenv("TRANSITION_PANEL_DIR", unset = default_data_dir)

# Where to write the output files (CSV with coefficients and PNG plot). By
# default the files are written to the current working directory, but the
# behaviour can be customised via the environment variable
# `TRANSITION_OUTPUT_DIR`.
output_dir <- Sys.getenv("TRANSITION_OUTPUT_DIR", unset = getwd())

if (!dir.exists(data_dir)) {

  stop(
    "The directory with the transition panels does not exist: ",
    data_dir,
    "\nUse Sys.setenv(TRANSITION_PANEL_DIR = 'path/to/panels') before running the script."
  )
}

if (!dir.exists(output_dir)) {
  dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
}


# ------------------------------
# Helper functions
# ------------------------------
parse_tpre <- function(file_name) {
  value <- stringr::str_extract(basename(file_name), "(?<=_)\\d+(?=\\.csv$)")
  ifelse(is.na(value), NA_integer_, as.integer(value))
}

build_shock_series <- function(max_period, t_pre) {
  shock <- rep(0, max_period)
  if (is.na(t_pre) || t_pre + 1 > max_period) {
    return(shock)
  }
  for (h in seq_len(shock_length)) {
    pos <- t_pre + h
    if (pos > max_period) {
      break
    }
    shock[pos] <- shock_size * (shock_decay^(h - 1))
  }
  shock * shock_scale

}

winsorize <- function(x, p = winsor_prob) {
  if (all(is.na(x))) {
    return(x)


  }
  lo <- stats::quantile(x, p, na.rm = TRUE)
  hi <- stats::quantile(x, 1 - p, na.rm = TRUE)
  pmin(pmax(x, lo), hi)
}

prepare_panel <- function(file_path) {
  raw <- readr::read_csv(
    file_path,
    col_names = FALSE,
    show_col_types = FALSE,
    progress = FALSE
  )

  names(raw) <- c(
    "firm_id", "quarter_id", "in_sample", "balanced_panel",
    "investment", "cash_flow", "market_value", "capital", "cash",
    "debt", "employment", "interest_rate", "unconstrained"
  )

  df <- raw %>%
    dplyr::filter(in_sample == 1) %>%
    dplyr::arrange(firm_id, quarter_id)

  df <- df %>%
    dplyr::mutate(
      log_capital = ifelse(capital > 0, log(capital), NA_real_),
      leverage = dplyr::if_else(capital != 0, debt / capital, NA_real_),
      cash_to_capital = dplyr::if_else(capital != 0, cash / capital, NA_real_)
    )

  df <- df %>%
    dplyr::mutate(
      leverage_win = winsorize(leverage),
      cash_to_capital_win = winsorize(cash_to_capital)
    ) %>%
    dplyr::group_by(firm_id) %>%
    dplyr::arrange(quarter_id, .by_group = TRUE) %>%
    dplyr::mutate(
      lag_log_capital = dplyr::lag(log_capital),
      lev_dm = leverage_win - mean(leverage_win, na.rm = TRUE),
      dd_dm = cash_to_capital_win - mean(cash_to_capital_win, na.rm = TRUE),
      lag_lev_dm = dplyr::lag(lev_dm),
      lag_dd_dm = dplyr::lag(dd_dm)
    ) %>%
    dplyr::ungroup()

  df
}

run_local_projection <- function(df, interaction_col, horizon) {
  response_col <- paste0("response_h", horizon)

  df_h <- df %>%
    dplyr::group_by(firm_id) %>%
    dplyr::mutate(!!response_col := dplyr::lead(log_capital, horizon) - lag_log_capital) %>%
    dplyr::ungroup()

  reg_data <- tibble::tibble(
    firm_id = df_h$firm_id,
    quarter_id = df_h$quarter_id,
    response = df_h[[response_col]],
    interaction = df_h[[interaction_col]]
  ) %>%
    dplyr::filter(!is.na(response), !is.na(interaction))

  if (nrow(reg_data) < 2L) {
    return(tibble(
      horizon = horizon,
      coefficient = NA_real_,
      std_error = NA_real_,
      n_obs = nrow(reg_data)
    ))
  }

  
  interaction_varies_within_period <- reg_data %>%
    dplyr::group_by(quarter_id) %>%
    dplyr::summarise(n_unique = dplyr::n_distinct(interaction), .groups = "drop") %>%
    dplyr::filter(n_unique > 1L) %>%
    nrow() > 0L
  
  interaction_varies_within_firm <- reg_data %>%
    dplyr::group_by(firm_id) %>%
    dplyr::summarise(n_unique = dplyr::n_distinct(interaction), .groups = "drop") %>%
    dplyr::filter(n_unique > 1L) %>%
    nrow() > 0L
  
  if (!interaction_varies_within_period || !interaction_varies_within_firm) {
    return(tibble(
      horizon = horizon,
      coefficient = NA_real_,
      std_error = NA_real_,
      n_obs = nrow(reg_data)
    ))
  }

  model <- fixest::feols(
     fml = response ~ interaction,
    data = reg_data,
    fixef = c("firm_id", "quarter_id"),
    cluster = ~firm_id
  )

  vcov_mat <- stats::vcov(model)
  coef_val <- stats::coef(model)["interaction"]
  se_val <- sqrt(diag(vcov_mat))["interaction"]
  
  tibble(
    horizon = horizon,
    coefficient = unname(coef_val),
    std_error = unname(se_val),
    n_obs = stats::nobs(model)
  )
}

# ------------------------------
# Main execution
# ------------------------------
panel_files <- list.files(
  path = data_dir,
  pattern = "^mTransitionPanel_\\d+\\.csv$",
  full.names = TRUE
)

if (length(panel_files) == 0) {
  stop(
    "No transition panel CSV files were found in ",
    data_dir,
    "."
  )
}

message("Processing ", length(panel_files), " transition panel(s) from: ", data_dir)

results <- purrr::map_dfr(panel_files, function(path) {
  t_pre <- parse_tpre(path)
  df <- prepare_panel(path)

  max_q <- max(df$quarter_id, na.rm = TRUE)
  shock_series <- build_shock_series(max_q, t_pre)

  df <- df %>%



























    dplyr::mutate(
      shock = shock_series[quarter_id],
      lev_shock = lag_lev_dm * shock,
      dd_shock = lag_dd_dm * shock
    )

  message("  • ", basename(path), " (t_pre = ", t_pre, ")")

  lev_results <- purrr::map_dfr(horizons, ~ run_local_projection(df, "lev_shock", .x)) %>%
    dplyr::mutate(measure = "leverage")
  
  dd_results <- purrr::map_dfr(horizons, ~ run_local_projection(df, "dd_shock", .x)) %>%
    dplyr::mutate(measure = "default_distance")
  
  dplyr::bind_rows(lev_results, dd_results) %>%
    dplyr::mutate(
      panel_file = basename(path),
      t_pre = t_pre
    )
})

weighted_mean_safe <- function(x, w) {
  valid <- !is.na(x) & !is.na(w) & w > 0
  if (!any(valid)) {
    return(NA_real_)
  }
  sum(x[valid] * w[valid]) / sum(w[valid])
}

summary_results <- results %>%
  dplyr::filter(!is.na(coefficient)) %>%
  dplyr::group_by(measure, horizon) %>%
  dplyr::summarise(
    coefficient = weighted_mean_safe(coefficient, n_obs),
    std_error = sqrt(weighted_mean_safe(std_error^2, n_obs)),
    n_obs = sum(n_obs, na.rm = TRUE),
    n_panels = dplyr::n_distinct(panel_file),
    .groups = "drop"
  ) %>%
  dplyr::mutate(
    ci_low = coefficient - 1.645 * std_error,
    ci_high = coefficient + 1.645 * std_error
  )

csv_path <- file.path(output_dir, "transition_panel_local_projections_simple.csv")
plot_path <- file.path(output_dir, "transition_panel_local_projections_simple.png")

readr::write_csv(results, csv_path)
message("Local projection estimates saved to: ", csv_path)

if (nrow(summary_results) == 0) {
  message("No valid regression results were produced, skipping the plot.")
} else {
  plot_results <- summary_results %>%
    dplyr::mutate(
      ribbon_low = coefficient - 1.645 * std_error,
      ribbon_high = coefficient + 1.645 * std_error,
      plot_horizon = horizon
    )

  build_panel_plot <- function(data, panel_title, colour, max_horizon) {
    ggplot(data, aes(x = plot_horizon, y = coefficient)) +
      geom_ribbon(
        aes(ymin = ribbon_low, ymax = ribbon_high),
        fill = colour,
        alpha = 0.2
      ) +
      geom_line(linewidth = 1, colour = colour) +
      geom_point(size = 2, colour = colour) +
      scale_x_continuous(
        breaks = 0:(max_horizon - 1),
        limits = c(0, max_horizon - 1),
        labels = function(x) x + 1
      ) +
      labs(
        title = panel_title,
        x = "Trimestres",
        y = "Efecto acumulado en la inversión"
      ) +
      theme_minimal(base_size = 13) +
      theme(
        panel.grid.minor = element_blank(),
        plot.title = element_text(face = "plain")
      )
  }
  
  plot_definitions <- list(
    leverage = list(title = "Panel (a): Heterogeneidad por apalancamiento", colour = "firebrick"),
    default_distance = list(title = "Panel (b): Heterogeneidad por distancia al default", colour = "steelblue")
  )


  plot_list <- purrr::imap(plot_definitions, function(def, measure_key) {
    data <- plot_results %>% dplyr::filter(measure == measure_key)
    if (nrow(data) == 0) {
      return(NULL)
    }
    build_panel_plot(data, def$title, def$colour, max_forecast_horizon)
  }) %>%
    purrr::compact()
  
  if (length(plot_list) == 0) {
    message("No valid regression results were produced, skipping the plot.")
  } else {
    figure_title <- paste0(
      "Figura 1: Heterogeneidad financiera en la dinámica de la inversión ante un shock monetario expansivo\n"
    )
    
    figure_obj <- patchwork::wrap_plots(plotlist = plot_list, nrow = 1) +
      patchwork::plot_annotation(
        title = figure_title,
        theme = theme(plot.title = element_text(face = "plain"))
      )
    
    print(figure_obj)
    ggplot2::ggsave(plot_path, figure_obj, width = 10, height = 5)
    message("Plot saved to: ", plot_path)
  }
  
}




























  figure_title <- paste0(
    "Figura 1: Heterogeneidad financiera en la dinámica de la inversión ante un shock monetario expansivo\n"
  )

  figure_obj <- ggplot(plot_results, aes(x = plot_horizon, y = coefficient, colour = measure, fill = measure)) +
    geom_ribbon(aes(ymin = ribbon_low, ymax = ribbon_high), alpha = 0.2, linewidth = 0) +
    geom_line(linewidth = 1) +








    geom_point(size = 2) +
    scale_x_continuous(
      breaks = seq_len(max_forecast_horizon),
      limits = c(1, max_forecast_horizon)
    ) +
    labs(
      title = figure_title,
      x = "Trimestres",
      y = "Efecto acumulado en la inversión",
      colour = "Medida",
      fill = "Medida"
    ) +
    theme_minimal(base_size = 13) +
    theme(
      panel.grid.minor = element_blank(),
      plot.title = element_text(face = "plain"),
      legend.position = "bottom"
    )








  print(figure_obj)
  ggplot2::ggsave(plot_path, figure_obj, width = 10, height = 5)
  message("Plot saved to: ", plot_path)
}