# =============================================================
# Simple Local Projections for Simulated Transition Path Panel
# =============================================================
#
# This script estimates very simple local projections using the simulated
# transition-path panels generated by the theoretical model. The goal is to
# measure how heterogeneity in firms' investment responses to a monetary shock
# varies with leverage and with a proxy for distance to default (cash buffers).
# The script only relies on the variables that are available in the simulated
# panels produced by `transition_path_panel.m`.
# =============================================================

suppressPackageStartupMessages({
  library(readr)
  library(dplyr)
  library(fixest)
  library(stringr)
  library(tibble)
  library(purrr)
})

# ------------------------------
# Configuration
# ------------------------------
# Horizons for the local projections (in quarters)
horizons <- 0:8
# Monetary shock profile (same as in the MATLAB/Do-file implementation)
shock_length <- 12
shock_size <- 0.0025
shock_decay <- 0.5
shock_scale <- -4  # flip sign and annualise

# ------------------------------
# Helper functions
# ------------------------------
parse_tpre <- function(file_name) {
  value <- stringr::str_extract(basename(file_name), "(?<=_)\\d+(?=\\.csv$)")
  ifelse(is.na(value), NA_integer_, as.integer(value))
}

build_shock_series <- function(max_period, t_pre) {
  shock <- rep(0, max_period)
  if (is.na(t_pre) || t_pre + 1 > max_period) {
    return(shock)
  }
  for (h in seq_len(shock_length)) {
    pos <- t_pre + h
    if (pos > max_period) {
      break
    }
    shock[pos] <- shock_size * (shock_decay^(h - 1))
  }
  shock * shock_scale
}

prepare_panel <- function(file_path) {
  raw <- readr::read_csv(
    file_path,
    col_names = FALSE,
    show_col_types = FALSE,
    progress = FALSE
  )

  names(raw) <- c(
    "firm_id", "quarter_id", "in_sample", "balanced_panel",
    "investment", "cash_flow", "market_value", "capital", "cash",
    "debt", "employment", "interest_rate", "unconstrained"
  )

  df <- raw %>%
    dplyr::filter(in_sample == 1) %>%
    dplyr::arrange(firm_id, quarter_id)

  df <- df %>%
    dplyr::mutate(
      log_capital = ifelse(capital > 0, log(capital), NA_real_),
      leverage = dplyr::if_else(capital != 0, debt / capital, NA_real_),
      cash_to_capital = dplyr::if_else(capital != 0, cash / capital, NA_real_)
    )

  df <- df %>%
    dplyr::group_by(firm_id) %>%
    dplyr::mutate(
      lev_within = leverage - mean(leverage, na.rm = TRUE),
      dd_within = cash_to_capital - mean(cash_to_capital, na.rm = TRUE),
      lag_log_capital = dplyr::lag(log_capital),
      lag_lev_within = dplyr::lag(lev_within),
      lag_dd_within = dplyr::lag(dd_within)
    ) %>%
    dplyr::ungroup()

  df
}

run_local_projection <- function(df, interaction_col, horizon) {
  response_col <- paste0("response_h", horizon)

  df_h <- df %>%
    dplyr::group_by(firm_id) %>%
    dplyr::mutate(!!response_col := dplyr::lead(log_capital, horizon) - lag_log_capital) %>%
    dplyr::ungroup()

  reg_data <- tibble::tibble(
    firm_id = df_h$firm_id,
    quarter_id = df_h$quarter_id,
    response = df_h[[response_col]],
    interaction = df_h[[interaction_col]]
  ) %>%
    dplyr::filter(!is.na(response), !is.na(interaction))
  
  if (nrow(reg_data) == 0) {
    return(tibble(
      horizon = horizon,
      coefficient = NA_real_,
      std_error = NA_real_,
      n_obs = 0L
    ))
  }

  model <- fixest::feols(
    fml = response ~ interaction,
    data = reg_data,
    fixef = ~firm_id + quarter_id,
    cluster = ~firm_id
  )

  vcov_mat <- stats::vcov(model)
  coef_val <- stats::coef(model)["interaction"]
  se_val <- sqrt(diag(vcov_mat))["interaction"]
  
  tibble(
    horizon = horizon,
    coefficient = unname(coef_val),
    std_error = unname(se_val),
    n_obs = stats::nobs(model)
  )
}

# ------------------------------
# Main execution
# ------------------------------
script_dir <- getwd()
panel_files <- list.files(
  path = script_dir,
  pattern = "^mTransitionPanel_\\d+\\.csv$",
  full.names = TRUE
)

if (length(panel_files) == 0) {
  stop("No transition panel CSV files were found in the current directory.")
}

results <- purrr::map_dfr(panel_files, function(path) {
  t_pre <- parse_tpre(path)
  df <- prepare_panel(path)

  max_q <- max(df$quarter_id, na.rm = TRUE)
  shock_series <- build_shock_series(max_q, t_pre)

  df <- df %>%
    dplyr::mutate(
      shock = shock_series[quarter_id],
      lev_shock = lag_lev_within * shock,
      dd_shock = lag_dd_within * shock
    )

  lev_results <- purrr::map_dfr(horizons, ~ run_local_projection(df, "lev_shock", .x)) %>%
    dplyr::mutate(measure = "leverage")

  dd_results <- purrr::map_dfr(horizons, ~ run_local_projection(df, "dd_shock", .x)) %>%
    dplyr::mutate(measure = "default_distance")

  dplyr::bind_rows(lev_results, dd_results) %>%
    dplyr::mutate(
      panel_file = basename(path),
      t_pre = t_pre
    )
})

output_path <- file.path(script_dir, "transition_panel_local_projections_simple.csv")
readr::write_csv(results, output_path)

message("Local projection estimates saved to: ", output_path)